title: Jacob's blog
email: edjacob25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   My blog
baseurl: /
url: "jacobrr.me"
twitter_username: jbrr25
github_username:  edjacob25
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
