title: Jacob Rivera's blog
author: Jacob Rivera
email: edjacob25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   I make posts about the technologies I'm using or experimenting with, mostly talking about the caveats
   and little things that I found.
baseurl:
url: "jacobrr.me"
twitter_username: jbrr25
github_username:  edjacob25
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
